### ISSUE TITLE
How to use 'Target model cache'

### ISSUE THREAD

**Issue by 9p15p** [andr345/frtm-vos#16]
Thank you for your wonderful code. I am a green hand, and I want to know: 

1. I can't find the place where we use the path of 'tmcache' in `training.py`

2. How can we use this cache(20GB) in training. 

Best wishes! ^_^

**Comment by andr345** [comment]
In train.py look in the ModelParameters class above the main function and you will find "self.tmodel_cache". This is where the path is stored first. You can also enable or disable the cache here,, or set it read-only, so that no new models are stored to disk.

If you want to see how the caching works, have a look in training_model.py, in TrainerModel._initialize(). This is where the target models are trained and cached.

Hope this helps!

**Comment by weirme** [comment]
Hello, I have download tmodels_cache(20GB) and set read_only=True, do I now use cache for training after this setting? I found output sps was only 1.21 and cache_hits was zero...  Is this normal? thanks :)
